name: elasticsearch

on:
  workflow_dispatch:

jobs:
  elasticsearch7:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - run: export SEARCH_ENGINE_DOCKERFILE="docker/elasticsearch/Dockerfile"; mvn verify -Dtest=none -DfailIfNoTests=false -Dit.test=IndexingIT
  elasticsearch8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - run: export SEARCH_ENGINE_DOCKERFILE="docker/elasticsearch8/Dockerfile"; mvn verify -Dtest=none -DfailIfNoTests=false -Dit.test=IndexingIT
  opensearch1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - run: mvn verify -Dtest=none -DfailIfNoTests=false -Dit.test=IndexingIT
  opensearch2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'
    - run: export SEARCH_ENGINE_DOCKERFILE="docker/opensearch2/Dockerfile"; mvn verify -Dtest=none -DfailIfNoTests=false -Dit.test=IndexingIT
