name: Maven Build

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - run: git clone -b FOLSPRINGS-161-spring-boot-3.4 --depth 1 https://github.com/folio-org/folio-spring-support.git
    - run: cd folio-spring-support; mvn -B -U -DskipTests install
    - run: mvn -B package
